"""
Upload Wave 1 brainwaves + pink noise to Supabase.
Generated by tools/aura/gen_brainwaves.sh on 2026-05-05.

Reads service_role key from KEYS_LOCAL.md.
"""
import re
import subprocess
import sys
from pathlib import Path
import requests

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parent.parent
KEYS = REPO / "KEYS_LOCAL.md"
PROJECT = "vzuwvsmlyigjtsearxym"
BASE = f"https://{PROJECT}.supabase.co"
BUCKET = "aura-audio"


def load_service_key() -> str:
    text = KEYS.read_text(encoding="utf-8")
    m = re.search(r"Service Role Key:\s*(\S+)", text)
    if not m:
        sys.exit("Could not find 'Service Role Key:' in KEYS_LOCAL.md")
    return m.group(1)


KEY = load_service_key()
HEADERS = {"apikey": KEY, "Authorization": f"Bearer {KEY}"}


def ffprobe_dur(p: Path) -> int:
    r = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=nokey=1:noprint_wrappers=1", str(p)],
        capture_output=True, text=True, check=True)
    return int(float(r.stdout.strip()))


def upload(file: Path, dest_path: str) -> str:
    url = f"{BASE}/storage/v1/object/{BUCKET}/{dest_path}"
    with open(file, "rb") as f:
        r = requests.post(
            url,
            headers={**HEADERS, "Content-Type": "audio/mpeg", "x-upsert": "true"},
            data=f, timeout=300,
        )
    if r.status_code not in (200, 201):
        raise RuntimeError(f"upload failed {r.status_code}: {r.text[:300]}")
    return f"{BASE}/storage/v1/object/public/{BUCKET}/{dest_path}"


def upsert(row: dict) -> None:
    url = f"{BASE}/rest/v1/aura_tracks"
    r = requests.post(
        url,
        headers={
            **HEADERS,
            "Content-Type": "application/json",
            "Prefer": "resolution=merge-duplicates",
        },
        json=[row], timeout=30,
    )
    if r.status_code not in (200, 201, 204):
        raise RuntimeError(f"upsert failed {r.status_code}: {r.text[:300]}")


# Track definitions — sort_order continues from existing max
# (frequency max=8 → start at 10; nature max=14 → pink_noise at 15)
TRACKS = [
    {
        "id": "brainwave_delta",
        "category": "frequency",
        "hz": None,
        "chakra": None,
        "color_hex": "#3B5BFF",
        "icon": "bedtime",
        "name_en": "Deep Sleep · Delta 2.5Hz",
        "name_es": "Sueño Profundo · Delta 2.5Hz",
        "desc_en": "Binaural beats at 2.5Hz — delta range — supports deep restorative sleep. Use with headphones.",
        "desc_es": "Tonos binaurales a 2.5Hz en rango delta — apoya el sueño profundo y reparador. Usa audífonos.",
        "license": "Originally generated by Pixora · CC0",
        "sort_order": 10,
        "file": "out/frequencies/brainwave_delta_2.5hz.mp3",
        "dest": "frequencies/brainwave_delta_2.5hz.mp3",
    },
    {
        "id": "brainwave_theta",
        "category": "frequency",
        "hz": None,
        "chakra": None,
        "color_hex": "#7C3AED",
        "icon": "self_improvement",
        "name_en": "Meditation · Theta 6Hz",
        "name_es": "Meditación · Theta 6Hz",
        "desc_en": "Binaural beats at 6Hz — theta range — induces meditative state and creative flow. Use with headphones.",
        "desc_es": "Tonos binaurales a 6Hz en rango theta — induce estado meditativo y flujo creativo. Usa audífonos.",
        "license": "Originally generated by Pixora · CC0",
        "sort_order": 11,
        "file": "out/frequencies/brainwave_theta_6hz.mp3",
        "dest": "frequencies/brainwave_theta_6hz.mp3",
    },
    {
        "id": "brainwave_schumann",
        "category": "frequency",
        "hz": None,
        "chakra": None,
        "color_hex": "#10B981",
        "icon": "public",
        "name_en": "Earth Resonance · Schumann 7.83Hz",
        "name_es": "Resonancia Terrestre · Schumann 7.83Hz",
        "desc_en": "Binaural beats at 7.83Hz — Earth's natural electromagnetic resonance. Grounding and balancing.",
        "desc_es": "Tonos binaurales a 7.83Hz — la resonancia electromagnética natural de la Tierra. Conexión y balance.",
        "license": "Originally generated by Pixora · CC0",
        "sort_order": 12,
        "file": "out/frequencies/brainwave_schumann_7.83hz.mp3",
        "dest": "frequencies/brainwave_schumann_7.83hz.mp3",
    },
    {
        "id": "brainwave_alpha",
        "category": "frequency",
        "hz": None,
        "chakra": None,
        "color_hex": "#06B6D4",
        "icon": "spa",
        "name_en": "Relaxed Awake · Alpha 10Hz",
        "name_es": "Relajación Consciente · Alpha 10Hz",
        "desc_en": "Binaural beats at 10Hz — alpha range — calm wakeful state for light meditation and stress relief.",
        "desc_es": "Tonos binaurales a 10Hz en rango alpha — estado consciente relajado para meditación ligera y alivio del estrés.",
        "license": "Originally generated by Pixora · CC0",
        "sort_order": 13,
        "file": "out/frequencies/brainwave_alpha_10hz.mp3",
        "dest": "frequencies/brainwave_alpha_10hz.mp3",
    },
    {
        "id": "brainwave_gamma",
        "category": "frequency",
        "hz": None,
        "chakra": None,
        "color_hex": "#F59E0B",
        "icon": "bolt",
        "name_en": "Peak Focus · Gamma 40Hz",
        "name_es": "Foco Máximo · Gamma 40Hz",
        "desc_en": "Binaural beats at 40Hz — gamma range — supports peak focus, learning and high cognitive performance.",
        "desc_es": "Tonos binaurales a 40Hz en rango gamma — apoya foco máximo, aprendizaje y alto desempeño cognitivo.",
        "license": "Originally generated by Pixora · CC0",
        "sort_order": 14,
        "file": "out/frequencies/brainwave_gamma_40hz.mp3",
        "dest": "frequencies/brainwave_gamma_40hz.mp3",
    },
    {
        "id": "noise_pink",
        "category": "nature",
        "hz": None,
        "chakra": None,
        "color_hex": "#EC4899",
        "icon": "graphic_eq",
        "name_en": "Pink Noise",
        "name_es": "Ruido Rosa",
        "desc_en": "Pink noise — softer than white noise, scientifically shown to improve sleep quality and memory consolidation.",
        "desc_es": "Ruido rosa — más suave que el blanco, científicamente comprobado para mejorar la calidad del sueño y consolidación de memoria.",
        "license": "Originally generated by Pixora · CC0",
        "sort_order": 15,
        "file": "out/frequencies/pink_noise.mp3",
        "dest": "nature/pink_noise.mp3",
    },
]


def main() -> None:
    print(f"Uploading {len(TRACKS)} tracks to {BUCKET}...")
    for t in TRACKS:
        local = ROOT / t["file"]
        if not local.exists():
            print(f"  ⚠ SKIP {t['id']} — file missing: {local}")
            continue
        dur = ffprobe_dur(local)
        url = upload(local, t["dest"])
        row = {
            "id": t["id"],
            "category": t["category"],
            "hz": t["hz"],
            "chakra": t["chakra"],
            "color_hex": t["color_hex"],
            "icon": t["icon"],
            "name_en": t["name_en"],
            "name_es": t["name_es"],
            "desc_en": t["desc_en"],
            "desc_es": t["desc_es"],
            "duration_sec": dur,
            "file_path": t["dest"],
            "audio_url": url,
            "license": t["license"],
            "sort_order": t["sort_order"],
        }
        upsert(row)
        print(f"  ✓ {t['id']:25s} {dur}s → {t['dest']}")
    print("Done.")


if __name__ == "__main__":
    main()
