# Gradle JVM args
org.gradle.jvmargs=-Xmx4G -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX
android.useAndroidX=true
android.enableJetifier=false

# Kotlin
kotlin.code.style=official

# R8 full mode
android.enableR8.fullMode=true

# Faster builds
android.nonFinalResIds=true
