"""Scaffold a new canvas_scene wallpaper.

Usage:
    python tools/wallpapers/create_canvas_scene.py <scene_id> [--src DIR]

Creates `tools/wallpapers/_tmp_<scene_id>/build_and_upload.py` pre-populated
with the canonical patterns + gotchas baked in:

  - Service-role key loaded from KEYS_LOCAL.md or env (NEVER hardcoded)
  - Image + preview filenames UNVERSIONED (required by
    WallpaperService._resolveCanvasSceneFromPath basename match)
  - Internal layers MAY be versioned (no longer required from v1.7.40+
    thanks to URL-meta diff in SceneSpecService — but kept as escape hatch)
  - Catalog INSERT_AT_FRONT so newest appears first in the 3D tab
  - FCM helper invoked correctly (`catalog wallpapers`)
  - Source asset dimensions printed for bounds_norm computation

Run the generated script directly to upload. Edit paste positions /
collision rules / motion params inline.
"""
import argparse
import sys
from pathlib import Path
from textwrap import dedent


TEMPLATE = dedent('''\
"""Build {scene_id} canvas_scene and publish to Supabase.

Generated by tools/wallpapers/create_canvas_scene.py.
Edit `main()` to set layer positions / sizes / motion / collision.
"""
import json
import os
import re
import sys
import urllib.request
import urllib.parse
from pathlib import Path
from PIL import Image

SRC = Path(r"{src_dir}")
OUT = Path(__file__).parent

URL = "https://vzuwvsmlyigjtsearxym.supabase.co"


def _load_service_role_key() -> str:
    key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")
    if key:
        return key
    keys_md = Path(r"D:/Orbix/Pixora-IA/KEYS_LOCAL.md")
    if not keys_md.exists():
        sys.exit("KEYS_LOCAL.md not found")
    m = re.search(r"Service Role Key:\\s*(eyJ[A-Za-z0-9_\\-\\.]+)",
                  keys_md.read_text(encoding="utf-8"))
    if not m:
        sys.exit("Service Role Key not found in KEYS_LOCAL.md")
    return m.group(1)


SR = _load_service_role_key()
H_AUTH = {{"apikey": SR, "Authorization": f"Bearer {{SR}}"}}

ID = "{scene_id}"
TARGET_W, TARGET_H = 1080, 2340


def make_layer(src_name: str, out_name: str, paste_box=None,
               target=(TARGET_W, TARGET_H)):
    """Place src into TARGET-sized transparent canvas.
    paste_box=None → cover-fit centered. paste_box=(x,y,w,h) → resize+pos."""
    src = Image.open(SRC / src_name).convert("RGBA")
    canvas = Image.new("RGBA", target, (0, 0, 0, 0))
    if paste_box is None:
        sr, tr = src.width / src.height, target[0] / target[1]
        if sr > tr:
            new_h = target[1]
            new_w = int(src.width * (new_h / src.height))
        else:
            new_w = target[0]
            new_h = int(src.height * (new_w / src.width))
        resized = src.resize((new_w, new_h), Image.LANCZOS)
        canvas.paste(resized, ((target[0] - new_w) // 2,
                               (target[1] - new_h) // 2), resized)
    else:
        x, y, w, h = paste_box
        canvas.paste(src.resize((w, h), Image.LANCZOS), (x, y),
                     src.resize((w, h), Image.LANCZOS))
    canvas.save(OUT / out_name, "WEBP", quality=88, method=6)
    print(f"  {{out_name}}: {{(OUT / out_name).stat().st_size // 1024}} KB")


def build_composite(layer_filenames: list[str]):
    """Composite layers (in order) into stable {{ID}}.webp + preview."""
    composite = Image.open(OUT / layer_filenames[0]).convert("RGBA")
    for fn in layer_filenames[1:]:
        composite = Image.alpha_composite(composite,
            Image.open(OUT / fn).convert("RGBA"))
    rgb = Image.new("RGB", composite.size, (0, 0, 0))
    rgb.paste(composite, mask=composite.split()[3])
    # STABLE NAMES — required for canvas_scene auto-upgrade. Do NOT version.
    rgb.save(OUT / f"{{ID}}.webp", "WEBP", quality=85, method=6)
    preview = rgb.copy()
    preview.thumbnail((540, 1170), Image.LANCZOS)
    preview.save(OUT / f"{{ID}}_preview.webp", "WEBP", quality=78, method=6)
    print(f"  composite + preview written (stable names, no version suffix)")


def upload(local: Path, bucket: str, key: str, ctype: str):
    url = f"{{URL}}/storage/v1/object/{{bucket}}/{{urllib.parse.quote(key)}}"
    body = local.read_bytes()
    req = urllib.request.Request(
        url, data=body,
        headers={{**H_AUTH, "Content-Type": ctype, "x-upsert": "true"}},
        method="POST")
    try:
        urllib.request.urlopen(req).read()
        print(f"  uploaded {{bucket}}/{{key}} ({{len(body)//1024}} KB)")
    except urllib.error.HTTPError as e:
        print(f"  FAIL: {{e.code}} {{e.read().decode()[:200]}}")


def write_scene_spec(spec: dict):
    spec_path = OUT / f"{{ID}}.json"
    spec_path.write_text(json.dumps(spec, indent=2, ensure_ascii=False),
                         encoding="utf-8")
    upload(spec_path, "wallpaper-scenes", f"{{ID}}.json", "application/json")


def patch_catalog_index(category: str, title_es: str, title_en: str,
                        tags: list[str]):
    public = f"{{URL}}/storage/v1/object/public/wallpaper-images/catalog_index.json"
    idx = json.loads(urllib.request.urlopen(public).read())
    idx["items"] = [it for it in idx["items"] if it.get("id") != ID]
    entry = {{
        "id": ID,
        "type": "canvas_scene",
        "schema": 1,
        "title": {{"en": title_en, "es": title_es}},
        "preview_url": f"{{URL}}/storage/v1/object/public/wallpaper-images/{{ID}}_preview.webp",
        "tags": tags,
        "category": category,
        "featured": True,
        "spec_url": f"{{URL}}/storage/v1/object/public/wallpaper-scenes/{{ID}}.json",
    }}
    # PREPEND so newest entries appear FIRST in the 3D tab listing.
    idx["items"].insert(0, entry)
    idx["version"] = idx.get("version", 0) + 1
    tmp = OUT / "catalog_index.json"
    tmp.write_text(json.dumps(idx, indent=2, ensure_ascii=False),
                   encoding="utf-8")
    print(f"  catalog v{{idx['version']}} ({{len(idx['items'])}} items)")
    upload(tmp, "wallpaper-images", "catalog_index.json", "application/json")


def fcm_push():
    import subprocess
    helper = Path(r"D:/Orbix/Pixora-IA/tools/wallpapers/_fcm_push.py")
    r = subprocess.run([sys.executable, str(helper), "catalog", "wallpapers"],
                       capture_output=True, text=True, encoding="utf-8")
    print(r.stdout.strip() or r.stderr.strip())


def main():
    # ─── 1) Inspect source PNG dims to plan paste positions ───────────────
    # for p in sorted(SRC.glob("*.png")):
    #     img = Image.open(p).convert("RGBA")
    #     print(f"{{p.name}}: {{img.size}} bbox={{img.split()[3].getbbox()}}")

    print("=== Building layers ===")
    # Sky / background — cover-fit centered:
    make_layer("BACKGROUND.png", f"{{ID}}_bg.webp")

    # Foreground subject — uncomment + tune paste_box for positioning:
    # subj_w = int(TARGET_W * 1.4)           # max ~1.4 to fit without sides crop
    # subj_h = int(subj_w * SRC_ASPECT)      # preserve aspect
    # paste_x = (TARGET_W - subj_w) // 2
    # paste_y = int(TARGET_H * 0.40) - (subj_h // 2)  # subj center at 40% height
    # make_layer("SUBJECT.png", f"{{ID}}_subj.webp",
    #            paste_box=(paste_x, paste_y, subj_w, subj_h))

    print("\\n=== Composite preview ===")
    build_composite([f"{{ID}}_bg.webp"])  # add foreground layers in order

    print("\\n=== Uploading images ===")
    for fn in [f"{{ID}}_bg.webp", f"{{ID}}.webp", f"{{ID}}_preview.webp"]:
        upload(OUT / fn, "wallpaper-images", fn, "image/webp")

    print("\\n=== Writing scene spec ===")
    spec = {{
        "schema_version": 1,
        "id": ID,
        "type": "canvas_scene",
        "title": {{"en": "TODO Title EN", "es": "TODO Title ES"}},
        "tags": ["TODO", "3d", "live"],
        "category": "TODO_CATEGORY",
        "featured": True,
        "background": {{
            "url": f"{{URL}}/storage/v1/object/public/wallpaper-images/{{ID}}.webp",
            "preview_url": f"{{URL}}/storage/v1/object/public/wallpaper-images/{{ID}}_preview.webp",
            "scroll": False,
        }},
        "image_layers": [
            {{
                "key": "bg",
                "url": f"{{URL}}/storage/v1/object/public/wallpaper-images/{{ID}}_bg.webp",
                "z": 0,
                "parallax_factor": 0.0,  # sky/bg = 0 to avoid bottom gap on tilt
                "scale": 1.0,
            }},
            # ── Layer with bob (passive floating) ────────────────────────
            # {{
            #     "key": "subj",
            #     "url": f"{{URL}}/storage/v1/object/public/wallpaper-images/{{ID}}_subj.webp",
            #     "z": 1,
            #     "parallax_factor": 0.6,
            #     "scale": 1.0,
            #     "bob_amplitude_px": 50,   # 5-7% of subject height max
            #     "bob_period_sec": 5.5,
            # }},
            # ── Layer with auto_jump (Mario-style) + collision pair ──────
            # {{
            #     "key": "character",
            #     "url": "...",
            #     "z": 4,
            #     "bounds_norm": {{"x": 0.65, "y": 0.79, "w": 0.15, "h": 0.10}},
            #     "motion": {{"kind": "auto_jump", "interval_s": 4.0,
            #                 "amplitude_px": 320, "duration_s": 0.85}},
            # }},
            # {{
            #     "key": "target",
            #     "url": "...",
            #     "z": 2,
            #     "bounds_norm": {{"x": 0.65, "y": 0.60, "w": 0.16, "h": 0.08}},
            #     "collision": {{"with_layer": "character", "action": "bump_up",
            #                    "amplitude_px": 25, "duration_s": 0.30,
            #                    "cooldown_s": 1.0}},
            # }},
        ],
        "sprites": [],
        "particles": [],
        "events": [],
    }}
    write_scene_spec(spec)

    print("\\n=== Patching catalog index ===")
    patch_catalog_index(
        category="TODO_CATEGORY",
        title_es="TODO Title ES",
        title_en="TODO Title EN",
        tags=["TODO", "3d", "live"],
    )

    print("\\n=== FCM ===")
    fcm_push()
    print(f"\\n[DONE] {{ID}} live.")


if __name__ == "__main__":
    main()
''')


def main():
    p = argparse.ArgumentParser()
    p.add_argument("scene_id", help="snake_case scene id, e.g. mario_nes_brinca")
    p.add_argument("--src", default=r"C:/Users/lalo/Desktop/wallPapers_repo/nuevos",
                   help="folder with source PNGs")
    args = p.parse_args()

    if not args.scene_id.replace("_", "").isalnum():
        sys.exit(f"Invalid scene_id: {args.scene_id} (only [a-z0-9_])")

    out_dir = Path(__file__).parent / f"_tmp_{args.scene_id}"
    out_dir.mkdir(exist_ok=True)
    out_file = out_dir / "build_and_upload.py"
    if out_file.exists():
        ans = input(f"{out_file} exists. Overwrite? [y/N] ")
        if ans.lower() != "y":
            sys.exit("aborted")

    content = TEMPLATE.format(scene_id=args.scene_id, src_dir=args.src)
    out_file.write_text(content, encoding="utf-8")
    print(f"Created: {out_file}")
    print(f"")
    print(f"Next steps:")
    print(f"  1. Drop source PNGs into: {args.src}/<theme>/")
    print(f"  2. Edit {out_file.name} — set layer URLs, paste positions, motion, collision")
    print(f"  3. Run: python {out_file}")
    print(f"")
    print(f"Rules baked into the template (do NOT override):")
    print(f"  - {{ID}}.webp + {{ID}}_preview.webp are STABLE NAMES (no _v suffix)")
    print(f"  - catalog entries are PREPENDED (newest first)")
    print(f"  - service role key loads from KEYS_LOCAL.md (never hardcoded)")
    print(f"  - FCM helper invoked with 'catalog wallpapers' (not just 'wallpapers')")


if __name__ == "__main__":
    main()
